# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8550-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter salami aston,$(TARGET_DEVICE)),)

endif
